"""Add file_hash to AnalysisHistory

Revision ID: 6f129d37bc2e
Revises: 76f0505b0254
Create Date: 2026-01-22 00:43:01.467875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f129d37bc2e'
down_revision: Union[str, Sequence[str], None] = '76f0505b0254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_history', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_analysis_history_file_hash'), 'analysis_history', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_history_file_hash'), table_name='analysis_history')
    op.drop_column('analysis_history', 'file_hash')
    # ### end Alembic commands ###
