"""add ai_calls_count and api_calls_count to usage_tracking

Revision ID: 87c87c6b196a
Revises: c13bf7677ff2
Create Date: 2026-01-20 08:22:49.047902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c87c6b196a'
down_revision: Union[str, Sequence[str], None] = 'c13bf7677ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_tracking', sa.Column('api_calls_count', sa.Integer(), nullable=True))
    op.add_column('usage_tracking', sa.Column('ai_calls_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_tracking', 'ai_calls_count')
    op.drop_column('usage_tracking', 'api_calls_count')
    # ### end Alembic commands ###
