"""add missing tables: activity_mapping batch_job code_review custom_rules

Revision ID: c13bf7677ff2
Revises: f772f0754df7
Create Date: 2026-01-19 22:51:46.602535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13bf7677ff2'
down_revision: Union[str, Sequence[str], None] = 'f772f0754df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_mappings',
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('source_activity', sa.String(), nullable=True),
    sa.Column('target_activity', sa.String(), nullable=True),
    sa.Column('compatibility_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_table('batch_jobs',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('processed_files', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('custom_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('code_reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('total_issues', sa.Integer(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_reviews')
    op.drop_table('custom_rules')
    op.drop_table('batch_jobs')
    op.drop_table('activity_mappings')
    # ### end Alembic commands ###
