"""add role to users

Revision ID: e13de6caf70f
Revises: d47ce51b91cf
Create Date: 2025-12-24 05:05:29.759919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13de6caf70f'
down_revision: Union[str, Sequence[str], None] = 'd47ce51b91cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Create ENUM type first
    user_role_enum = sa.Enum('ADMIN', 'USER', name='userrole')
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # 2. Add column using the ENUM
    op.add_column(
        'users',
        sa.Column('user_role', user_role_enum, nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
